### Get ticket
POST {{baseUrl}}/access/ticket
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}

### Get instance resources
GET {{baseUrl}}/cluster/{{testvmpath}}

### Test create instance

POST {{baseUrl}}/cluster/{{testvmpath}}/create
Content-Type: application/x-www-form-urlencoded

name=testvm
&pool={{poolname}}
&cores=8
&memory=8192

### Test fail create instance

POST {{baseUrl}}/cluster/{{testvmpath}}/create
Content-Type: application/x-www-form-urlencoded

name=testvm
&pool={{poolname}}
&cores=9999
&memory=8192

### Test delete instance

DELETE {{baseUrl}}/cluster/{{testvmpath}}/delete